In [1]:
import pandas as pd 
df = pd.read_csv("/Users/mac/desktop/project/company_data/second_week/data_csv/강원특별자치도_미용업.csv", encoding="CP949")

In [17]:
common_cols = {'개방서비스명', '휴업종료일자', '재개업일자', '개방서비스아이디', '소재지전체주소', '소재지전화', '도로명전체주소', '상세영업상태코드', '폐업일자', '인허가취소일자', '소재지우편번호', '데이터갱신일자', '휴업시작일자', '좌표정보y(epsg5174)', '업태구분명', '최종수정시점', '관리번호', '상세영업상태명', '개방자치단체코드', '데이터갱신구분', '인허가일자', '영업상태구분코드', '도로명우편번호', '좌표정보x(epsg5174)', '영업상태명', '번호', '소재지면적', '사업장명'}
common_cols = list(common_cols)
info = {}

for col in common_cols:
    series = df[col]
    dytype = series.dtype
    info[col]={"dytype":str(dytype),}
info
pd.DataFrame(info).T

                  dytype
소재지전체주소           object
사업장명              object
개방자치단체코드           int64
영업상태구분코드           int64
인허가취소일자          float64
상세영업상태코드           int64
관리번호              object
도로명우편번호          float64
재개업일자            float64
번호                 int64
개방서비스명            object
도로명전체주소           object
개방서비스아이디          object
폐업일자              object
휴업종료일자           float64
휴업시작일자           float64
업태구분명             object
인허가일자             object
좌표정보x(epsg5174)  float64
좌표정보y(epsg5174)  float64
데이터갱신일자           object
최종수정시점            object
소재지전화             object
영업상태명             object
데이터갱신구분           object
상세영업상태명           object
소재지면적            float64
소재지우편번호           object

In [21]:
df["개방자치단체코드"].unique()

array([4191000, 4241000, 4211000, 4301000, 4311000, 4201000, 4231000,
       4181000, 4331000, 4351000, 4251000, 4261000, 4281000, 4271000,
       4221000, 4321000, 4291000, 4341000])

In [30]:
df1 = df["개방자치단체코드"]
df2 = df["소재지전체주소"]
pd.DataFrame({"주소": df2, "코드": df1})

                                  주소       코드
0             강원특별자치도 원주시 단구동 1582-7  4191000
1      강원특별자치도 삼척시 정상동 356-2 강부3차아파트  4241000
2       강원특별자치도 동해시 천곡동 802-1 동해유공타워  4211000
3            강원특별자치도 동해시 천곡동 1058-28  4211000
4          강원특별자치도 철원군 철원읍 화지리 45-75  4301000
...                              ...      ...
12323          강원특별자치도 원주시 명륜동 276-2  4191000
12324         강원특별자치도 강릉시 홍제동 1022-1  4201000
12325         강원특별자치도 원주시 평원동 252-17  4191000
12326         강원특별자치도 강릉시 포남동 1297-7  4201000
12327  강원특별자치도 원주시 명륜동 847-2 현진에버빌3차  4191000

[12328 rows x 2 columns]

In [33]:
df["영업상태구분코드"].unique()

array([1, 3])

In [35]:
df1 = df["영업상태구분코드"]
df2 = df["영업상태명"]
pd.DataFrame(df1,df2)

       영업상태구분코드
영업상태명
영업/정상       NaN
영업/정상       NaN
영업/정상       NaN
영업/정상       NaN
영업/정상       NaN
...         ...
폐업          NaN
폐업          NaN
폐업          NaN
폐업          NaN
폐업          NaN

[12328 rows x 1 columns]

In [38]:
df["영업상태구분코드"].notna()

0        True
1        True
2        True
3        True
4        True
         ...
12323    True
12324    True
12325    True
12326    True
12327    True
Name: 영업상태구분코드, Length: 12328, dtype: bool