In [168]:
import pandas as pd
import os
df = pd.read_csv("/Users/mac/Desktop/project/company_data/second_week/data_csv/강원특별자치도_미용업.csv", encoding = "cp949")

In [169]:
import pandas as pd
common_columns = {'개방서비스명', '휴업종료일자', '재개업일자', '개방서비스아이디', '소재지전체주소', '소재지전화', '도로명전체주소', '상세영업상태코드', '폐업일자', '인허가취소일자', '소재지우편번호', '데이터갱신일자', '휴업시작일자', '좌표정보y(epsg5174)', '업태구분명', '최종수정시점', '관리번호', '상세영업상태명', '개방자치단체코드', '데이터갱신구분', '인허가일자', '영업상태구분코드', '도로명우편번호', '좌표정보x(epsg5174)', '영업상태명', '번호', '소재지면적', '사업장명'}
common_columns = list(common_columns)
df_common = df[common_columns]
df_common.head()

,개방서비스명,재개업일자,소재지면적,데이터갱신구분,번호,상세영업상태명,영업상태구분코드,사업장명,휴업종료일자,업태구분명,...,도로명우편번호,최종수정시점,인허가일자,도로명전체주소,영업상태명,개방서비스아이디,개방자치단체코드,인허가취소일자,좌표정보y(epsg5174),데이터갱신일자
0,미용업,NaN,92.38,U,1,영업,1,치크비비,NaN,피부미용업,...,26486.0,2024-12-16 13:02:31,2023-08-30,"강원특별자치도 원주시 구곡길 56, 1층 (단구동)",영업/정상,05_18_01_P,4191000,NaN,425040.403461,2024-12-18 02:40:00
1,미용업,NaN,25.50,I,2,영업,1,유월의네일,NaN,네일아트업,...,25925.0,2023-07-26 16:49:55,2023-07-26,"강원특별자치도 삼척시 동해대로 4122-18, 강부3차아파트 다동 2층 201호 (...",영업/정상,05_18_01_P,4241000,NaN,440634.623337,2023-07-28 00:18:47
2,미용업,NaN,19.79,I,3,영업,1,라움,NaN,일반미용업,...,25759.0,2023-08-16 09:50:01,2023-03-28,"강원특별자치도 동해시 천곡1길 3, 1층 111호 (천곡동, 동해유공타워)",영업/정상,05_18_01_P,4211000,NaN,449002.117936,2023-08-18 00:18:28
3,미용업,NaN,49.99,I,4,영업,1,네일아띠 nail atti,NaN,네일아트업,...,25766.0,2023-09-08 13:09:13,2023-09-08,"강원특별자치도 동해시 한섬로 43-1, 1층 (천곡동)",영업/정상,05_18_01_P,4211000,NaN,448517.056316,2023-09-10 00:18:09
4,미용업,NaN,6.44,I,5,영업,1,퀸네일(Queen nail),NaN,네일아트업,...,24006.0,2023-07-26 10:26:48,2023-07-26,강원특별자치도 철원군 철원읍 금학로255번길 19-16,영업/정상,05_18_01_P,4301000,NaN,523041.810348,2023-07-28 00:18:47

In [170]:
df["업태구분명"].value_counts()

업태구분명
일반미용업     8787
피부미용업     1961
네일아트업     1052
메이크업업      364
기타         160
미용업 기타       4
Name: count, dtype: int64

#### 폐업률 계산

In [171]:
total = len(df)
closed = len(df[df["영업상태명"] == "폐업"])
rate = closed/total *100
rate #폐업률 계산

50.86794289422453

#### 결측치 없도록 공통컬럼을 다시 구성 (폐업일자는 일단 제외..)

In [172]:
cols =  ["사업장명", "개방서비스명", "업태구분명", "영업상태명", "인허가일자", "도로명전체주소", "좌표정보x(epsg5174)", "좌표정보y(epsg5174)"]
df_cols = df[cols].dropna()
df_cols

,사업장명,개방서비스명,업태구분명,영업상태명,인허가일자,도로명전체주소,좌표정보x(epsg5174),좌표정보y(epsg5174)
0,치크비비,미용업,피부미용업,영업/정상,2023-08-30,"강원특별자치도 원주시 구곡길 56, 1층 (단구동)",284085.774483,425040.403461
1,유월의네일,미용업,네일아트업,영업/정상,2023-07-26,"강원특별자치도 삼척시 동해대로 4122-18, 강부3차아파트 다동 2층 201호 (...",392799.721848,440634.623337
2,라움,미용업,일반미용업,영업/정상,2023-03-28,"강원특별자치도 동해시 천곡1길 3, 1층 111호 (천곡동, 동해유공타워)",386712.289280,449002.117936
3,네일아띠 nail atti,미용업,네일아트업,영업/정상,2023-09-08,"강원특별자치도 동해시 한섬로 43-1, 1층 (천곡동)",386356.850962,448517.056316
4,퀸네일(Queen nail),미용업,네일아트업,영업/정상,2023-07-26,강원특별자치도 철원군 철원읍 금학로255번길 19-16,218621.857158,523041.810348
...,...,...,...,...,...,...,...,...
12323,오늘헤어,미용업,일반미용업,폐업,2025-01-14,"강원특별자치도 원주시 남원로 593, 1층 (명륜동)",284093.646798,426487.620702
12324,리즈살롱,미용업,피부미용업,폐업,2024-12-12,"강원특별자치도 강릉시 선수촌로 73, 205호 (홍제동)",364727.938171,474427.111455
12325,제이영,미용업,일반미용업,폐업,2024-12-03,"강원특별자치도 원주시 중평길 62, 1층 (평원동)",284324.532497,428063.499731
12326,뮤스킨,미용업,피부미용업,폐업,2024-12-10,"강원특별자치도 강릉시 하평6길 59, 1층 (포남동)",368689.465509,476294.704654
12327,루베르뷰티,미용업,피부미용업,폐업,2024-11-18,"강원특별자치도 원주시 남원로 441-15, 현진에버빌3차 상가동 1층 104호 (명륜동)",283131.757263,425310.858363

In [173]:
df.groupby("업태구분명")["영업상태명"].value_counts()

업태구분명   영업상태명
기타      영업/정상      83
        폐업         77
네일아트업   영업/정상     671
        폐업        381
메이크업업   영업/정상     259
        폐업        105
미용업 기타  폐업          3
        영업/정상       1
일반미용업   폐업       4650
        영업/정상    4137
피부미용업   폐업       1055
        영업/정상     906
Name: count, dtype: int64

In [174]:
df1 = df.dropna(subset=["좌표정보x(epsg5174)", "좌표정보y(epsg5174)", "소재지전체주소"]).copy()
df1["시군"] = df1["소재지전체주소"].str.split().str[1]
df1["시군"].head()

0    원주시
1    삼척시
2    동해시
3    동해시
4    철원군
Name: 시군, dtype: object

#### 시군별 업소수

In [175]:
df2 = df1["시군"].value_counts()
df2

시군
원주시    3006
춘천시    2499
강릉시    1917
동해시     841
속초시     688
삼척시     414
홍천군     404
철원군     296
태백시     291
영월군     199
평창군     192
정선군     180
횡성군     172
인제군     156
고성군     137
양구군     118
양양군     115
화천군     100
동구        1
제천시       1
Name: count, dtype: int64

#### 시군별 업태 개수

In [176]:
df3 = pd.crosstab(df1["시군"], df1["업태구분명"])
df3

업태구분명  기타  네일아트업  메이크업업  미용업 기타  일반미용업  피부미용업
시군
강릉시    45    179     52       0   1303    338
고성군     3      6      0       0    115     13
동구      0      0      0       0      1      0
동해시     5     59     27       1    612    137
삼척시     7     22      5       0    315     65
속초시    13     68     34       0    459    114
양구군     0      9      0       0     88     21
양양군     5      6      0       0     88     16
영월군     0      9      2       0    157     31
원주시    45    324    112       0   1973    552
인제군     0     15      3       0    119     19
정선군     2      7      2       0    142     27
제천시     0      0      0       0      0      1
철원군     6     22      2       0    228     38
춘천시     8    231     95       0   1767    398
태백시     1     24      6       3    230     27
평창군     4     16      2       0    146     24
홍천군    13     25      8       0    300     58
화천군     0      6      3       0     72     19
횡성군     1     14      5       0    126     26

#### 시군별 폐업 업소 수

In [177]:
df4 = df1[df1["폐업일자"].notna()]
df5 = df1[df1["폐업일자"].isna()]
df6 = df4["시군"].value_counts()
df6

시군
원주시    1408
춘천시    1263
강릉시     941
동해시     434
속초시     318
홍천군     208
삼척시     206
철원군     151
태백시     141
영월군     104
평창군      91
정선군      89
횡성군      82
고성군      77
인제군      75
양구군      56
양양군      53
화천군      48
동구        1
제천시       1
Name: count, dtype: int64

#### 시군별 폐업률

In [178]:
df7 = df1["시군"].value_counts()
df8 = (df6/df7 * 100).sort_values(ascending=False)
df8

시군
제천시    100.000000
동구     100.000000
고성군     56.204380
영월군     52.261307
동해시     51.605232
홍천군     51.485149
철원군     51.013514
춘천시     50.540216
삼척시     49.758454
정선군     49.444444
강릉시     49.087115
태백시     48.453608
인제군     48.076923
화천군     48.000000
횡성군     47.674419
양구군     47.457627
평창군     47.395833
원주시     46.839654
속초시     46.220930
양양군     46.086957
Name: count, dtype: float64

#### 시군별, 업태별 폐업률

In [186]:
df["시군"] = df["소재지전체주소"].str.split().str[1]
total = df.groupby(["시군","업태구분명"]).size()
closed = df[df["폐업일자"].notna()].groupby(["시군","업태구분명"]).size()
rate = (closed/total *100).fillna(0)
df1 = rate.reset_index(name="폐업률")
df1

     시군  업태구분명         폐업률
0   강릉시     기타   38.297872
1   강릉시  네일아트업   34.806630
2   강릉시  메이크업업   26.415094
3   강릉시  일반미용업   51.895911
4   강릉시  피부미용업   54.678363
..  ...    ...         ...
82  횡성군     기타  100.000000
83  횡성군  네일아트업   42.857143
84  횡성군  메이크업업   60.000000
85  횡성군  일반미용업   49.253731
86  횡성군  피부미용업   53.846154

[87 rows x 3 columns]