##### 미용업 기준으로 찾음

In [15]:
import pandas as pd 
import glob
import os
df = pd.read_csv("/Users/mac/desktop/project/company_data/second_week/data_csv/강원특별자치도_미용업.csv", encoding="CP949")

In [ ]:
common_cols = {'개방서비스명', '휴업종료일자', '재개업일자', '개방서비스아이디', '소재지전체주소', '소재지전화', '도로명전체주소', '상세영업상태코드', '폐업일자', '인허가취소일자', '소재지우편번호', '데이터갱신일자', '휴업시작일자', '좌표정보y(epsg5174)', '업태구분명', '최종수정시점', '관리번호', '상세영업상태명', '개방자치단체코드', '데이터갱신구분', '인허가일자', '영업상태구분코드', '도로명우편번호', '좌표정보x(epsg5174)', '영업상태명', '번호', '소재지면적', '사업장명'}
common_cols = list(common_cols)
info = {}

for col in common_cols:
    series = df[col]
    dytype = series.dtype
    info[col]={"dytype":str(dytype),}
info
pd.DataFrame(info).T

                  dytype
데이터갱신구분           object
개방서비스아이디          object
영업상태명             object
좌표정보y(epsg5174)  float64
데이터갱신일자           object
좌표정보x(epsg5174)  float64
소재지전체주소           object
최종수정시점            object
인허가취소일자          float64
재개업일자            float64
개방자치단체코드           int64
상세영업상태코드           int64
업태구분명             object
개방서비스명            object
소재지우편번호           object
영업상태구분코드           int64
번호                 int64
도로명전체주소           object
관리번호              object
사업장명              object
소재지전화             object
도로명우편번호          float64
휴업종료일자           float64
소재지면적            float64
상세영업상태명           object
인허가일자             object
휴업시작일자           float64
폐업일자              object

In [17]:
df["개방자치단체코드"].unique()

array([4191000, 4241000, 4211000, 4301000, 4311000, 4201000, 4231000,
       4181000, 4331000, 4351000, 4251000, 4261000, 4281000, 4271000,
       4221000, 4321000, 4291000, 4341000])

In [18]:
df1 = df["개방자치단체코드"]
df2 = df["소재지전체주소"]
pd.DataFrame({"주소": df2, "코드": df1})

                                  주소       코드
0             강원특별자치도 원주시 단구동 1582-7  4191000
1      강원특별자치도 삼척시 정상동 356-2 강부3차아파트  4241000
2       강원특별자치도 동해시 천곡동 802-1 동해유공타워  4211000
3            강원특별자치도 동해시 천곡동 1058-28  4211000
4          강원특별자치도 철원군 철원읍 화지리 45-75  4301000
...                              ...      ...
12323          강원특별자치도 원주시 명륜동 276-2  4191000
12324         강원특별자치도 강릉시 홍제동 1022-1  4201000
12325         강원특별자치도 원주시 평원동 252-17  4191000
12326         강원특별자치도 강릉시 포남동 1297-7  4201000
12327  강원특별자치도 원주시 명륜동 847-2 현진에버빌3차  4191000

[12328 rows x 2 columns]

In [19]:
df["영업상태구분코드"].unique()

array([1, 3])

In [20]:
df["상세영업상태코드"].unique()

array([1, 2])

#### 휴업: 2,3 // 폐업: 3,2 // 영업 정상: 1

In [21]:
df1 = df["영업상태명"]
df2 = df["영업상태구분코드"]
df3 = df["상세영업상태코드"]
pd.DataFrame({"영업상태명": df1,"영업상태구분코드": df2, "상세영업상태코드":df3})

       영업상태명  영업상태구분코드  상세영업상태코드
0      영업/정상         1         1
1      영업/정상         1         1
2      영업/정상         1         1
3      영업/정상         1         1
4      영업/정상         1         1
...      ...       ...       ...
12323     폐업         3         2
12324     폐업         3         2
12325     폐업         3         2
12326     폐업         3         2
12327     폐업         3         2

[12328 rows x 3 columns]

In [22]:
df["개방서비스명"].unique()

array(['미용업'], dtype=object)

In [23]:
df["업태구분명"].unique()

array(['피부미용업', '네일아트업', '일반미용업', '메이크업업', '기타', '미용업 기타'], dtype=object)

#### epsg 5174: 지도, 주소, 공간 데이터에 쓰는 공식 좌표 시스템 중에 하나임. 미터 단위의 좌표값
#### 좌표정보x는 동쪽, y는 북쪽
#### 한국 중앙측 (127.5°) 기준 평면으로 변환된 절대 위치

In [24]:
df = df.set_index("사업장명")
df1 = df["좌표정보y(epsg5174)"]
df2 = df["좌표정보x(epsg5174)"]
df3 = df["개방서비스명"]
df4 = df["업태구분명"]
pd.DataFrame({"좌표x": df2,"좌표y": df1,"서비스명": df3,"업태구분명": df4})

                           좌표x            좌표y 서비스명  업태구분명
사업장명
치크비비             284085.774483  425040.403461  미용업  피부미용업
유월의네일            392799.721848  440634.623337  미용업  네일아트업
라움               386712.289280  449002.117936  미용업  일반미용업
네일아띠 nail atti   386356.850962  448517.056316  미용업  네일아트업
퀸네일(Queen nail)  218621.857158  523041.810348  미용업  네일아트업
...                        ...            ...  ...    ...
오늘헤어             284093.646798  426487.620702  미용업  일반미용업
리즈살롱             364727.938171  474427.111455  미용업  피부미용업
제이영              284324.532497  428063.499731  미용업  일반미용업
뮤스킨              368689.465509  476294.704654  미용업  피부미용업
루베르뷰티            283131.757263  425310.858363  미용업  피부미용업

[12328 rows x 4 columns]

#### U: 갱신,I: 신규등록

In [25]:
df["데이터갱신구분"].unique()

array(['U', 'I'], dtype=object)

#### 관리번호: 개방자치단체코드-업태종류-인허가연도-?

In [26]:
df["인허가일자"]

사업장명
치크비비               2023-08-30
유월의네일              2023-07-26
라움                 2023-03-28
네일아띠 nail atti     2023-09-08
퀸네일(Queen nail)    2023-07-26
                      ...
오늘헤어               2025-01-14
리즈살롱               2024-12-12
제이영                2024-12-03
뮤스킨                2024-12-10
루베르뷰티              2024-11-18
Name: 인허가일자, Length: 12328, dtype: object

In [27]:
df1= df["관리번호"]
df2 = df["개방자치단체코드"]
pd.DataFrame({"관리번호": df1, "개방자치단체코드": df2})

                                   관리번호  개방자치단체코드
사업장명
치크비비             4191000-212-2023-00025   4191000
유월의네일            4241000-215-2023-00001   4241000
라움               4211000-213-2023-00003   4211000
네일아띠 nail atti   4211000-215-2023-00004   4211000
퀸네일(Queen nail)  4301000-213-2023-00002   4301000
...                                 ...       ...
오늘헤어             4191000-211-2025-00002   4191000
리즈살롱             4201000-212-2024-00009   4201000
제이영              4191000-213-2024-00053   4191000
뮤스킨              4201000-212-2024-00008   4201000
루베르뷰티            4191000-212-2024-00026   4191000

[12328 rows x 2 columns]

In [28]:
nb_name = ['미용업', '즉석판매제조가공업', '농어촌민박업', '통신판매업', '담배도매업', '건강기능식품유통전문판매업', '가축사육업', '일반음식점', '휴게음식점']
csv_folder = "/Users/mac/Desktop/project/company_data/second_week/data_csv"
csv_files = glob.glob(os.path.join(csv_folder,"*.csv"))

target_csv = []

for nb in nb_name:
    for csv in csv_files:
        if nb in csv:
            target_csv.append(csv)
target_csv = [f for f in target_csv if "동물미용업" not in f]
target_csv

['/Users/mac/Desktop/project/company_data/second_week/data_csv/강원특별자치도_미용업.csv',
 '/Users/mac/Desktop/project/company_data/second_week/data_csv/강원특별자치도_즉석판매제조가공업.csv',
 '/Users/mac/Desktop/project/company_data/second_week/data_csv/강원특별자치도_농어촌민박업.csv',
 '/Users/mac/Desktop/project/company_data/second_week/data_csv/강원특별자치도_통신판매업.csv',
 '/Users/mac/Desktop/project/company_data/second_week/data_csv/강원특별자치도_담배도매업.csv',
 '/Users/mac/Desktop/project/company_data/second_week/data_csv/강원특별자치도_가축사육업.csv',
 '/Users/mac/Desktop/project/company_data/second_week/data_csv/강원특별자치도_일반음식점.csv',
 '/Users/mac/Desktop/project/company_data/second_week/data_csv/강원특별자치도_휴게음식점.csv']

#### 업종명마다 어떤 업태구분명이 있는지 확인함

In [29]:
rows = []
for csv in target_csv:
    df = pd.read_csv(csv, encoding= "CP949", on_bad_lines="skip")
    df.columns=df.columns.str.strip()

    if "개방서비스명" in df.columns and "업태구분명" in df.columns:
        업종명 = csv.split("_")[-1].replace(".csv","")

        for svc, up in zip(df["개방서비스명"], df["업태구분명"]):
            rows.append([업종명, svc, up])
cols = ["업종명", "개방서비스명", "업태구분명"]
result = pd.DataFrame(rows, columns=["업종명", "개방서비스명", "업태구분명"])
result

/var/folders/sc/_dk299z14xs6j6n9ggl_ny5r0000gn/T/ipykernel_94806/1217605649.py:3: DtypeWarning: Columns (31,32) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv, encoding= "CP949", on_bad_lines="skip")
/var/folders/sc/_dk299z14xs6j6n9ggl_ny5r0000gn/T/ipykernel_94806/1217605649.py:3: DtypeWarning: Columns (11,17,44,45) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv, encoding= "CP949", on_bad_lines="skip")
/var/folders/sc/_dk299z14xs6j6n9ggl_ny5r0000gn/T/ipykernel_94806/1217605649.py:3: DtypeWarning: Columns (39,44) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv, encoding= "CP949", on_bad_lines="skip")

          업종명 개방서비스명     업태구분명
0         미용업    미용업     피부미용업
1         미용업    미용업     네일아트업
2         미용업    미용업     일반미용업
3         미용업    미용업     네일아트업
4         미용업    미용업     네일아트업
...       ...    ...       ...
232765  휴게음식점  휴게음식점  기타 휴게음식점
232766  휴게음식점  휴게음식점    일반조리판매
232767  휴게음식점  휴게음식점  기타 휴게음식점
232768  휴게음식점  휴게음식점  기타 휴게음식점
232769  휴게음식점  휴게음식점        다방

[232770 rows x 3 columns]