In [17]:
import pandas as pd
import os
df = pd.read_csv("/Users/mac/Desktop/project/company_data/second_week/data_csv/강원특별자치도_미용업.csv", encoding = "cp949")

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12328 entries, 0 to 12327
Data columns (total 45 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   번호               12328 non-null  int64
 1   개방서비스명           12328 non-null  object
 2   개방서비스아이디         12328 non-null  object
 3   개방자치단체코드         12328 non-null  int64
 4   관리번호             12328 non-null  object
 5   인허가일자            12328 non-null  object
 6   인허가취소일자          0 non-null      float64
 7   영업상태구분코드         12328 non-null  int64
 8   영업상태명            12328 non-null  object
 9   상세영업상태코드         12328 non-null  int64
 10  상세영업상태명          12328 non-null  object
 11  폐업일자             6269 non-null   object
 12  휴업시작일자           0 non-null      float64
 13  휴업종료일자           0 non-null      float64
 14  재개업일자            0 non-null      float64
 15  소재지전화            7468 non-null   object
 16  소재지면적            12283 non-null  float64
 17  소재지우편번호          2 non-null      object
 18  소재지전체주소          12289 non-null  object
 19  도로명전체주소          9506 non-null   object
 20  도로명우편번호          9446 non-null   float64
 21  사업장명             12328 non-null  object
 22  최종수정시점           12328 non-null  object
 23  데이터갱신구분          12328 non-null  object
 24  데이터갱신일자          12328 non-null  object
 25  업태구분명            12328 non-null  object
 26  좌표정보x(epsg5174)  11765 non-null  float64
 27  좌표정보y(epsg5174)  11765 non-null  float64
 28  위생업태명            12328 non-null  object
 29  건물지상층수           12328 non-null  int64
 30  건물지하층수           12328 non-null  int64
 31  사용시작지상층          12328 non-null  int64
 32  사용끝지상층           12328 non-null  int64
 33  사용시작지하층          12328 non-null  int64
 34  사용끝지하층           12328 non-null  int64
 35  의자수              12328 non-null  int64
 36  조건부허가신고사유        12 non-null     object
 37  조건부허가시작일자        17 non-null     float64
 38  조건부허가종료일자        24 non-null     float64
 39  건물소유구분명          5627 non-null   object
 40  여성종사자수           12328 non-null  int64
 41  남성종사자수           12328 non-null  int64
 42  침대수              12328 non-null  int64
 43  다중이용업소여부         12328 non-null  object
 44  Unnamed: 44      0 non-null      float64
dtypes: float64(11), int64(14), object(20)
memory usage: 4.2+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12328 entries, 0 to 12327
Data columns (total 45 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   번호               12328 non-null  int64
 1   개방서비스명           12328 non-null  object
 2   개방서비스아이디         12328 non-null  object
 3   개방자치단체코드         12328 non-null  int64
 4   관리번호             12328 non-null  object
 5   인허가일자            12328 non-null  object
 6   인허가취소일자          0 non-null      float64
 7   영업상태구분코드         12328 non-null  int64
 8   영업상태명            12328 non-null  object
 9   상세영업상태코드         12328 non-null  int64
 10  상세영업상태명          12328 non-null  object
 11  폐업일자             6269 non-null   object
 12  휴업시작일자           0 non-null      float64
 13  휴업종료일자           0 non-null      float64
 14  재개업일자            0 non-null      float64
 15  소재지전화            7468 non-null   object
 16  소재지면적            12283 non-null  float64
 17  소재지우편번호          2 non-null      object
 18  소재지전체주소          12289 non-null  object
 19  도로명전체주소          9506 non-null   object
 20  도로명우편번호          9446 non-null   float64
 21  사업장명             12328 non-null  object
 22  최종수정시점           12328 non-null  object
 23  데이터갱신구분          12328 non-null  object
 24  데이터갱신일자          12328 non-null  object
 25  업태구분명            12328 non-null  object
 26  좌표정보x(epsg5174)  11765 non-null  float64
 27  좌표정보y(epsg5174)  11765 non-null  float64
 28  위생업태명            12328 non-null  object
 29  건물지상층수           12328 non-null  int64
 30  건물지하층수           12328 non-null  int64
 31  사용시작지상층          12328 non-null  int64
 32  사용끝지상층           12328 non-null  int64
 33  사용시작지하층          12328 non-null  int64
 34  사용끝지하층           12328 non-null  int64
 35  의자수              12328 non-null  int64
 36  조건부허가신고사유        12 non-null     object
 37  조건부허가시작일자        17 non-null     float64
 38  조건부허가종료일자        24 non-null     float64
 39  건물소유구분명          5627 non-null   object
 40  여성종사자수           12328 non-null  int64
 41  남성종사자수           12328 non-null  int64
 42  침대수              12328 non-null  int64
 43  다중이용업소여부         12328 non-null  object
 44  Unnamed: 44      0 non-null      float64
dtypes: float64(11), int64(14), object(20)
memory usage: 4.2+ MB

Empty DataFrame
Columns: []
Index: []

In [19]:
common_columns = {'개방서비스명', '휴업종료일자', '재개업일자', '개방서비스아이디', '소재지전체주소', '소재지전화', '도로명전체주소', '상세영업상태코드', '폐업일자', '인허가취소일자', '소재지우편번호', '데이터갱신일자', '휴업시작일자', '좌표정보y(epsg5174)', '업태구분명', '최종수정시점', '관리번호', '상세영업상태명', '개방자치단체코드', '데이터갱신구분', '인허가일자', '영업상태구분코드', '도로명우편번호', '좌표정보x(epsg5174)', '영업상태명', '번호', '소재지면적', '사업장명'}
common_columns = list(common_columns)
df_common = df[common_columns]
df_common.head()

,상세영업상태명,데이터갱신일자,최종수정시점,소재지면적,관리번호,번호,데이터갱신구분,사업장명,인허가취소일자,폐업일자,...,좌표정보x(epsg5174),재개업일자,휴업종료일자,좌표정보y(epsg5174),도로명전체주소,소재지전화,도로명우편번호,인허가일자,업태구분명,영업상태명
0,영업,2024-12-18 02:40:00,2024-12-16 13:02:31,92.38,4191000-212-2023-00025,1,U,치크비비,NaN,NaN,...,284085.774483,NaN,NaN,425040.403461,"강원특별자치도 원주시 구곡길 56, 1층 (단구동)",NaN,26486.0,2023-08-30,피부미용업,영업/정상
1,영업,2023-07-28 00:18:47,2023-07-26 16:49:55,25.50,4241000-215-2023-00001,2,I,유월의네일,NaN,NaN,...,392799.721848,NaN,NaN,440634.623337,"강원특별자치도 삼척시 동해대로 4122-18, 강부3차아파트 다동 2층 201호 (...",NaN,25925.0,2023-07-26,네일아트업,영업/정상
2,영업,2023-08-18 00:18:28,2023-08-16 09:50:01,19.79,4211000-213-2023-00003,3,I,라움,NaN,NaN,...,386712.289280,NaN,NaN,449002.117936,"강원특별자치도 동해시 천곡1길 3, 1층 111호 (천곡동, 동해유공타워)",NaN,25759.0,2023-03-28,일반미용업,영업/정상
3,영업,2023-09-10 00:18:09,2023-09-08 13:09:13,49.99,4211000-215-2023-00004,4,I,네일아띠 nail atti,NaN,NaN,...,386356.850962,NaN,NaN,448517.056316,"강원특별자치도 동해시 한섬로 43-1, 1층 (천곡동)",NaN,25766.0,2023-09-08,네일아트업,영업/정상
4,영업,2023-07-28 00:18:47,2023-07-26 10:26:48,6.44,4301000-213-2023-00002,5,I,퀸네일(Queen nail),NaN,NaN,...,218621.857158,NaN,NaN,523041.810348,강원특별자치도 철원군 철원읍 금학로255번길 19-16,NaN,24006.0,2023-07-26,네일아트업,영업/정상

In [20]:
df["업태구분명"].value_counts()

업태구분명
일반미용업     8787
피부미용업     1961
네일아트업     1052
메이크업업      364
기타         160
미용업 기타       4
Name: count, dtype: int64

#### 폐업률 계산

In [21]:
total = len(df)
closed = len(df[df["영업상태명"] == "폐업"])
rate = closed/total *100
rate #폐업률 계산

50.86794289422453

#### 결측치 없도록 공통컬럼을 다시 구성 (폐업일자는 일단 제외..)

In [22]:
cols =  ["사업장명", "개방서비스명", "업태구분명", "영업상태명", "인허가일자", "도로명전체주소", "좌표정보x(epsg5174)", "좌표정보y(epsg5174)"]
df_cols = df[cols].dropna()
df_cols

,사업장명,개방서비스명,업태구분명,영업상태명,인허가일자,도로명전체주소,좌표정보x(epsg5174),좌표정보y(epsg5174)
0,치크비비,미용업,피부미용업,영업/정상,2023-08-30,"강원특별자치도 원주시 구곡길 56, 1층 (단구동)",284085.774483,425040.403461
1,유월의네일,미용업,네일아트업,영업/정상,2023-07-26,"강원특별자치도 삼척시 동해대로 4122-18, 강부3차아파트 다동 2층 201호 (...",392799.721848,440634.623337
2,라움,미용업,일반미용업,영업/정상,2023-03-28,"강원특별자치도 동해시 천곡1길 3, 1층 111호 (천곡동, 동해유공타워)",386712.289280,449002.117936
3,네일아띠 nail atti,미용업,네일아트업,영업/정상,2023-09-08,"강원특별자치도 동해시 한섬로 43-1, 1층 (천곡동)",386356.850962,448517.056316
4,퀸네일(Queen nail),미용업,네일아트업,영업/정상,2023-07-26,강원특별자치도 철원군 철원읍 금학로255번길 19-16,218621.857158,523041.810348
...,...,...,...,...,...,...,...,...
12323,오늘헤어,미용업,일반미용업,폐업,2025-01-14,"강원특별자치도 원주시 남원로 593, 1층 (명륜동)",284093.646798,426487.620702
12324,리즈살롱,미용업,피부미용업,폐업,2024-12-12,"강원특별자치도 강릉시 선수촌로 73, 205호 (홍제동)",364727.938171,474427.111455
12325,제이영,미용업,일반미용업,폐업,2024-12-03,"강원특별자치도 원주시 중평길 62, 1층 (평원동)",284324.532497,428063.499731
12326,뮤스킨,미용업,피부미용업,폐업,2024-12-10,"강원특별자치도 강릉시 하평6길 59, 1층 (포남동)",368689.465509,476294.704654
12327,루베르뷰티,미용업,피부미용업,폐업,2024-11-18,"강원특별자치도 원주시 남원로 441-15, 현진에버빌3차 상가동 1층 104호 (명륜동)",283131.757263,425310.858363

In [23]:
df.groupby("업태구분명")["영업상태명"].value_counts()

업태구분명   영업상태명
기타      영업/정상      83
        폐업         77
네일아트업   영업/정상     671
        폐업        381
메이크업업   영업/정상     259
        폐업        105
미용업 기타  폐업          3
        영업/정상       1
일반미용업   폐업       4650
        영업/정상    4137
피부미용업   폐업       1055
        영업/정상     906
Name: count, dtype: int64

In [24]:
df1 = df.dropna(subset=["좌표정보x(epsg5174)", "좌표정보y(epsg5174)", "소재지전체주소"]).copy()
df1["시군"] = df1["소재지전체주소"].str.split().str[1]
df1["시군"].head()

0    원주시
1    삼척시
2    동해시
3    동해시
4    철원군
Name: 시군, dtype: object

#### 시군별 업소수

In [25]:
df2 = df1["시군"].value_counts()
df2

시군
원주시    3006
춘천시    2499
강릉시    1917
동해시     841
속초시     688
삼척시     414
홍천군     404
철원군     296
태백시     291
영월군     199
평창군     192
정선군     180
횡성군     172
인제군     156
고성군     137
양구군     118
양양군     115
화천군     100
동구        1
제천시       1
Name: count, dtype: int64

#### 시군별 업태 개수

In [26]:
df3 = pd.crosstab(df1["시군"], df1["업태구분명"])
df3

업태구분명  기타  네일아트업  메이크업업  미용업 기타  일반미용업  피부미용업
시군
강릉시    45    179     52       0   1303    338
고성군     3      6      0       0    115     13
동구      0      0      0       0      1      0
동해시     5     59     27       1    612    137
삼척시     7     22      5       0    315     65
속초시    13     68     34       0    459    114
양구군     0      9      0       0     88     21
양양군     5      6      0       0     88     16
영월군     0      9      2       0    157     31
원주시    45    324    112       0   1973    552
인제군     0     15      3       0    119     19
정선군     2      7      2       0    142     27
제천시     0      0      0       0      0      1
철원군     6     22      2       0    228     38
춘천시     8    231     95       0   1767    398
태백시     1     24      6       3    230     27
평창군     4     16      2       0    146     24
홍천군    13     25      8       0    300     58
화천군     0      6      3       0     72     19
횡성군     1     14      5       0    126     26

#### 시군별 폐업 업소 수

In [27]:
df4 = df1[df1["폐업일자"].notna()]
df5 = df1[df1["폐업일자"].isna()]
df6 = df4["시군"].value_counts()
df6

시군
원주시    1408
춘천시    1263
강릉시     941
동해시     434
속초시     318
홍천군     208
삼척시     206
철원군     151
태백시     141
영월군     104
평창군      91
정선군      89
횡성군      82
고성군      77
인제군      75
양구군      56
양양군      53
화천군      48
동구        1
제천시       1
Name: count, dtype: int64

#### 시군별 폐업률

In [28]:
df7 = df1["시군"].value_counts()
df8 = (df6/df7 * 100).sort_values(ascending=False)
df8

시군
제천시    100.000000
동구     100.000000
고성군     56.204380
영월군     52.261307
동해시     51.605232
홍천군     51.485149
철원군     51.013514
춘천시     50.540216
삼척시     49.758454
정선군     49.444444
강릉시     49.087115
태백시     48.453608
인제군     48.076923
화천군     48.000000
횡성군     47.674419
양구군     47.457627
평창군     47.395833
원주시     46.839654
속초시     46.220930
양양군     46.086957
Name: count, dtype: float64

#### 시군별, 업태별 폐업률

In [29]:
df["시군"] = df["소재지전체주소"].str.split().str[1]
total = df.groupby(["시군","업태구분명"]).size()
closed = df[df["폐업일자"].notna()].groupby(["시군","업태구분명"]).size()
rate = (closed/total *100).fillna(0)
df1 = rate.reset_index(name="폐업률")
df1

     시군  업태구분명         폐업률
0   강릉시     기타   38.297872
1   강릉시  네일아트업   34.806630
2   강릉시  메이크업업   26.415094
3   강릉시  일반미용업   51.895911
4   강릉시  피부미용업   54.678363
..  ...    ...         ...
82  횡성군     기타  100.000000
83  횡성군  네일아트업   42.857143
84  횡성군  메이크업업   60.000000
85  횡성군  일반미용업   49.253731
86  횡성군  피부미용업   53.846154

[87 rows x 3 columns]