In [25]:
import pandas as pd
import os 

df = pd.read_csv("/Users/mac/Desktop/project/company_data/second_week/data_csv/강원특별자치도_담배도매업.csv", encoding="CP949")

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 31 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   번호               60 non-null     int64
 1   개방서비스명           60 non-null     object
 2   개방서비스아이디         60 non-null     object
 3   개방자치단체코드         60 non-null     int64
 4   관리번호             60 non-null     int64
 5   인허가일자            60 non-null     object
 6   인허가취소일자          0 non-null      float64
 7   영업상태구분코드         60 non-null     int64
 8   영업상태명            60 non-null     object
 9   상세영업상태코드         60 non-null     int64
 10  상세영업상태명          60 non-null     object
 11  폐업일자             27 non-null     object
 12  휴업시작일자           0 non-null      float64
 13  휴업종료일자           0 non-null      float64
 14  재개업일자            0 non-null      float64
 15  소재지전화            42 non-null     object
 16  소재지면적            0 non-null      float64
 17  소재지우편번호          52 non-null     object
 18  소재지전체주소          57 non-null     object
 19  도로명전체주소          53 non-null     object
 20  도로명우편번호          18 non-null     object
 21  사업장명             60 non-null     object
 22  최종수정시점           60 non-null     object
 23  데이터갱신구분          60 non-null     object
 24  데이터갱신일자          60 non-null     object
 25  업태구분명            0 non-null      float64
 26  좌표정보x(epsg5174)  56 non-null     float64
 27  좌표정보y(epsg5174)  56 non-null     float64
 28  취급제품명            60 non-null     object
 29  담배공급업체명          60 non-null     object
 30  Unnamed: 30      0 non-null      float64
dtypes: float64(9), int64(5), object(17)
memory usage: 14.7+ KB

In [27]:
common_columns = {'개방서비스명', '휴업종료일자', '재개업일자', '개방서비스아이디', '소재지전체주소', '소재지전화', '도로명전체주소', '상세영업상태코드', '폐업일자', '인허가취소일자', '소재지우편번호', '데이터갱신일자', '휴업시작일자', '좌표정보y(epsg5174)', '업태구분명', '최종수정시점', '관리번호', '상세영업상태명', '개방자치단체코드', '데이터갱신구분', '인허가일자', '영업상태구분코드', '도로명우편번호', '좌표정보x(epsg5174)', '영업상태명', '번호', '소재지면적', '사업장명'}
common_columns = list(common_columns)
df_common = df[common_columns]
df_common.head(3)

,소재지우편번호,개방서비스아이디,인허가취소일자,개방서비스명,인허가일자,영업상태명,개방자치단체코드,최종수정시점,도로명전체주소,소재지전화,...,폐업일자,상세영업상태코드,재개업일자,휴업종료일자,소재지전체주소,좌표정보x(epsg5174),좌표정보y(epsg5174),번호,상세영업상태명,영업상태구분코드
0,200-043,11_43_01_P,NaN,담배도매업,1989-05-27,영업/정상,4181000,2008-07-11 14:46:45,강원특별자치도 춘천시 중앙로 125 (중앙로3가),55-7612,...,NaN,1,NaN,NaN,강원특별자치도 춘천시 중앙로3가 66번지 14호,263390.344283,486177.855056,1,정상영업,1
1,200-060,11_43_01_P,NaN,담배도매업,1989-05-29,영업/정상,4181000,2008-07-11 14:46:10,강원특별자치도 춘천시 서부대성로 95-18 (교동),51-2153,...,NaN,1,NaN,NaN,강원특별자치도 춘천시 교동 55번지 2호,264416.630298,486758.884049,2,정상영업,1
2,200-755,11_43_01_P,NaN,담배도매업,1994-02-04,영업/정상,4181000,2008-07-11 15:02:24,NaN,57-3753,...,NaN,1,NaN,NaN,강원특별자치도 춘천시 후평동 주공5단지아파트 506동 206호,NaN,NaN,3,정상영업,1

In [28]:
df["업태구분명"].unique()

array([nan])

#### 여기는 업태구분명이 없어서 공통컬럼에서 뺏음.. 이 부분은 어떻게 해야 할 지 모르겠어요..

In [29]:
cols = ["사업장명", "개방서비스명", "영업상태명", "인허가일자", "도로명전체주소", "좌표정보x(epsg5174)", "좌표정보y(epsg5174)"]
df_cols = df[cols].dropna()
df_cols.head(10)

,사업장명,개방서비스명,영업상태명,인허가일자,도로명전체주소,좌표정보x(epsg5174),좌표정보y(epsg5174)
0,천마상사,담배도매업,영업/정상,1989-05-27,강원특별자치도 춘천시 중앙로 125 (중앙로3가),263390.344283,486177.855056
1,동양상사,담배도매업,영업/정상,1989-05-29,강원특별자치도 춘천시 서부대성로 95-18 (교동),264416.630298,486758.884049
3,재영상사,담배도매업,영업/정상,1998-10-19,강원특별자치도 춘천시 칠전서1길 37 (칠전동),262739.536723,482574.535709
5,마스크상사,담배도매업,영업/정상,2000-08-30,강원특별자치도 춘천시 칠전서1길 37 (칠전동),262739.536723,482574.535709
6,(주)재영상사,담배도매업,영업/정상,2004-06-22,강원특별자치도 춘천시 칠전서1길 37 (칠전동),262739.536723,482574.535709
7,에버필 강원,담배도매업,영업/정상,2005-05-07,강원특별자치도 춘천시 삭주로205번길 12 (후평동),266148.516446,487528.142315
8,타박앤패밀리,담배도매업,영업/정상,2007-07-06,"강원특별자치도 춘천시 안마산로 213, B27호 (퇴계동,퇴계타운)",264855.838698,483301.263497
9,(주)호반인터내셔널,담배도매업,영업/정상,2008-01-10,강원특별자치도 춘천시 삭주로70번길 41 (효자동),265018.333358,486623.936817
10,스누스코리아(강원북부총판),담배도매업,영업/정상,2013-10-02,강원특별자치도 춘천시 서부대성로 169-1 (효자동),264851.610718,486176.295874
11,파스타바코 춘천점,담배도매업,영업/정상,2015-03-23,"강원특별자치도 춘천시 중앙로 지하 33 (중앙로1가, 나열 44호)",264063.076082,486899.162452

#### 시군별 영업 상태

In [30]:
df["시군"] = df["소재지전체주소"].str.split().str[1]
df.groupby("시군")["영업상태명"].value_counts()

시군   영업상태명
강릉시  영업/정상     5
     폐업        3
고성군  영업/정상     1
동해시  폐업        2
속초시  폐업        2
양구군  폐업        1
양양군  폐업        2
영월군  폐업        2
원주시  영업/정상     6
     폐업        5
인제군  폐업        1
정선군  영업/정상     3
철원군  영업/정상     1
     폐업        1
춘천시  영업/정상    14
     폐업        6
태백시  폐업        1
홍천군  폐업        1
Name: count, dtype: int64

#### 시군별 폐업률
##### 폐업률 말이 안 되는데.. 어디서 잘못한 건지 모르겠어요..

In [31]:
total = df.groupby("시군")["시군"].count()
closed = df[df["폐업일자"].notna()].groupby("시군")["폐업일자"].count()
rate = (closed/total * 100).fillna(0)
df1 = rate.reset_index(name="폐업률")
df1

     시군         폐업률
0   강릉시   37.500000
1   고성군    0.000000
2   동해시  100.000000
3   속초시  100.000000
4   양구군  100.000000
5   양양군  100.000000
6   영월군  100.000000
7   원주시   45.454545
8   인제군  100.000000
9   정선군    0.000000
10  철원군   50.000000
11  춘천시   30.000000
12  태백시  100.000000
13  홍천군  100.000000