In [3]:
from sqlalchemy import create_engine
import pandas as pd

engine = create_engine("mysql+pymysql://root:fls0413!@localhost:3306/dashboard")
pd.read_sql("SHOW TABLES;", engine)

  Tables_in_dashboard
0           bus_stops
1      near_bus_stops
2         restaurants

In [4]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://root:fls0413!@localhost:3306/dashboard")

df_min = pd.read_sql("""
SELECT 사업장명, MIN(거리) AS 최소거리
FROM near_bus_stops
GROUP BY 사업장명;
""", engine)

df_min.head()

      사업장명      최소거리
0       청재  0.032810
1    두리감자탕  0.042326
2  약사촌 닭갈비  0.045904
3      산마루  0.030107
4     58전집  0.071927

#### 지역별(시군구) 평균 접근성

In [5]:
df_sigungu = pd.read_sql("""
SELECT r.sigungu, AVG(t.최소거리) AS 평균최소거리
FROM (
  SELECT 사업장명, MIN(거리) AS 최소거리
  FROM near_bus_stops
  GROUP BY 사업장명
) t
JOIN restaurants r ON t.사업장명 = r.사업장명
GROUP BY r.sigungu
ORDER BY 평균최소거리;
""", engine)

df_sigungu.head()

  sigungu    평균최소거리
0     원주시  0.044224
1     속초시  0.045988
2     인제군  0.049164
3     고성군  0.051282
4     춘천시  0.052514

#### 업종별 평균 접근성 한 번

In [6]:
df_upjong = pd.read_sql("""
SELECT r.업태구분명, AVG(t.최소거리) AS 평균최소거리
FROM (
  SELECT 사업장명, MIN(거리) AS 최소거리
  FROM near_bus_stops
  GROUP BY 사업장명
) t
JOIN restaurants r ON t.사업장명 = r.사업장명
GROUP BY r.업태구분명
ORDER BY 평균최소거리;
""", engine)

df_upjong.head()

     업태구분명    평균최소거리
0       횟집  0.008283
1  탕류(보신용)  0.035794
2       기타  0.045988
3       한식  0.051935
4    호프/통닭  0.061869

#### 저장

In [7]:
df_min.to_csv("result_min_distance_by_store.csv", index=False)
df_sigungu.to_csv("result_avg_distance_by_sigungu.csv", index=False)
df_upjong.to_csv("result_avg_distance_by_category.csv", index=False)

#### 오랜만에 돌아오니까 gpg failed to sign the data error가 뜸.. 고치다가 너무 산으로 가는 거 같아서 새로 코드스페이스 생성.. 나중에 어떻게 해결하는지 물어봐야지 꼭