##### JOIN TEST

In [2]:
# 분석용 기본 세팅
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://root:fls0413!@localhost:3306/dashboard")

In [3]:
query = """
SELECT r.사업장명, b.정류장명, n.거리
FROM near_bus_stops n
JOIN restaurants r ON n.사업장명 = r.사업장명
JOIN bus_stops b ON n.정류장ID = b.정류장
LIMIT 20;
"""

df_join = pd.read_sql(query, engine)
df_join

   사업장명    정류장명        거리
0   산마루  푸른언덕공원  0.030107
1   산마루  푸른언덕공원  0.030107
2   산마루  푸른언덕공원  0.030107
3   산마루  푸른언덕공원  0.030107
4   산마루  푸른언덕공원  0.030107
5   산마루  푸른언덕공원  0.030107
6   산마루  푸른언덕공원  0.030107
7   산마루  푸른언덕공원  0.030107
8   산마루  푸른언덕공원  0.030107
9   산마루  푸른언덕공원  0.030107
10  산마루  푸른언덕공원  0.030107
11  산마루  푸른언덕공원  0.030107
12  산마루  푸른언덕공원  0.030107
13  산마루  푸른언덕공원  0.030107
14  산마루  푸른언덕공원  0.030107
15  산마루  푸른언덕공원  0.030107
16  산마루  푸른언덕공원  0.030107
17  산마루  푸른언덕공원  0.030107
18  산마루  푸른언덕공원  0.030107
19  산마루  푸른언덕공원  0.030107

##### 음식점별 가까운 정류장

In [4]:
df_min_dist = pd.read_sql("""
SELECT 사업장명, MIN(거리) AS 최소거리
FROM near_bus_stops
GROUP BY 사업장명;
""", engine)

df_min_dist.head()

      사업장명      최소거리
0       청재  0.032810
1    두리감자탕  0.042326
2  약사촌 닭갈비  0.045904
3      산마루  0.030107
4     58전집  0.071927

#### 지역별 평균 접근성

In [5]:
df_region = pd.read_sql("""
SELECT r.sigungu, AVG(n.거리) AS 평균거리
FROM near_bus_stops n
JOIN restaurants r ON n.사업장명 = r.사업장명
GROUP BY r.sigungu;
""", engine)

df_region

   sigungu      평균거리
0      삼척시  0.053334
1      속초시  0.045988
2      춘천시  0.051693
3      원주시  0.044224
4      홍천군  0.053929
5      횡성군  0.061869
6      정선군  0.061869
7      고성군  0.051282
8      평창군  0.053929
9      인제군  0.049164
10     강릉시  0.053334
11     철원군  0.061869
12     태백시  0.061869
13     화천군  0.061869
14     양구군  0.061869
15     양양군  0.061869

#### 지도 시각화용 데이터

In [6]:
df_map = pd.read_sql("""
SELECT 
    r.사업장명, r.lat AS 업소_lat, r.lng AS 업소_lng,
    b.정류장명, b.위도 AS 정류_lat, b.경도 AS 정류_lng,
    n.거리
FROM near_bus_stops n
JOIN restaurants r ON n.사업장명 = r.사업장명
JOIN bus_stops b ON n.정류장ID = b.정류장;
""", engine)

df_map.head()

  사업장명     업소_lat      업소_lng    정류장명    정류_lat     정류_lng        거리
0  산마루  37.447784  129.174386  푸른언덕공원  37.87622  127.74556  0.030107
1  산마루  37.447784  129.174386  푸른언덕공원  37.87622  127.74556  0.030107
2  산마루  37.447784  129.174386  푸른언덕공원  37.87622  127.74556  0.030107
3  산마루  37.447784  129.174386  푸른언덕공원  37.87622  127.74556  0.030107
4  산마루  37.447784  129.174386  푸른언덕공원  37.87622  127.74556  0.030107